### ISSUE TITLE
Missing export for components

### ISSUE THREAD

**Issue by theaddonn** [brenoepics/vitepress-carbon#46]
I am currently trying to automate the creation of a sidebar, reading files and folders and then dynamically creating a list of `CarbonTheme.SidebarItem[]`.. tho it seems like I can not import the theme via `import {CarbonTheme} from "vitepress-carbon/dist/theme/CarbonTheme";` Is there any way to fix this?

**Comment by brenoepics** [comment]
Sorry for the delay, bump vitepress-carbon to `1.5.0` and it might work fine.
